// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.0;

import {Test, stdError} from "forge-std/Test.sol";
import {FridayEndOfMonthCadence} from "../../src/ratifiers/policies/FridayEndOfMonthCadence.sol";
import {
    SECONDS_PER_DAY,
    BOUNDARY_TIME_OF_DAY,
    DOMAIN_START,
    DOMAIN_END,
    FIXTURE_ENTRY_COUNT,
    isFridayAt
} from "../helpers/CadenceTestConstants.sol";

/// @dev No-dependency variant, validated against a hardcoded golden fixture rather than a Solidity reference.
/// Every expected boundary in test/fixtures/last_friday_boundaries.txt was generated by Python's calendar/datetime
/// modules (see the sibling .py), which share no code and no algorithm with the contract's inlined Hinnant math.
/// The test therefore contains NO civil-date arithmetic of its own: it treats the file as the specification and
/// checks the contract reproduces it exactly, so a bug common to the contract and any hand-written Solidity
/// reference cannot hide. Coverage beyond the fixture's horizon is structural (properties, not exact values).
contract FridayEndOfMonthCadenceTest is Test {
    FridayEndOfMonthCadence cadence;

    /// @dev Hardcoded boundaries loaded from the fixture (2025-01 .. 2125-12, last Friday of month, 15:00:00 UTC).
    uint256[] internal boundaries;

    function setUp() public {
        cadence = new FridayEndOfMonthCadence(BOUNDARY_TIME_OF_DAY);
        string[] memory lines = vm.split(vm.readFile("test/fixtures/last_friday_boundaries.txt"), "\n");
        for (uint256 i; i < lines.length; ++i) {
            if (bytes(lines[i]).length == 0) continue; // trailing newline
            boundaries.push(vm.parseUint(lines[i]));
        }
        // Exact count, so a truncated or blank-line-corrupted fixture cannot load silently.
        assertEq(boundaries.length, FIXTURE_ENTRY_COUNT, "fixture failed to load");
    }

    /// @dev Guards the oracle itself: the fixture must be strictly increasing, every entry a Friday at 15:00:00
    /// UTC, and consecutive entries 28 or 35 days apart. This weekday check is a plain epoch-day parity, not the
    /// contract's month algorithm, so it independently catches a corrupted or mis-generated file.
    function test_fixtureIsWellFormed() public view {
        for (uint256 i; i < boundaries.length; ++i) {
            uint256 b = boundaries[i];
            assertTrue(isFridayAt(b, BOUNDARY_TIME_OF_DAY), "not a Friday at 15:00:00 UTC");
            if (i > 0) {
                uint256 gap = b - boundaries[i - 1];
                assertTrue(gap == 28 days || gap == 35 days, "gap is not four or five weeks");
            }
        }
    }

    /// @dev The core check: every hardcoded boundary is an exact fixed point, one second later still maps to it,
    /// most of the period maps back, and one second before maps to the previous fixture entry. No date math here -
    /// the expected values come entirely from the file.
    function test_everyBoundaryMatchesFixture() public view {
        for (uint256 i; i < boundaries.length; ++i) {
            uint256 b = boundaries[i];
            assertEq(cadence.cadencePeriodStart(b), b);
            assertEq(cadence.cadencePeriodStart(b + 1), b);
            assertEq(cadence.cadencePeriodStart(b + 27 days), b); // shortest period is 28 days
            if (i > 0) assertEq(cadence.cadencePeriodStart(b - 1), boundaries[i - 1]);
        }
    }

    /// @dev Continuous differential fuzz against the fixture: for any timestamp inside the covered range, the
    /// contract must return the largest hardcoded boundary at or before it (found by binary search over the file).
    function testFuzz_matchesFixture(uint256 timestamp) public view {
        // Only the covered range: past the last entry the true boundary (next month) is not in the file.
        timestamp = bound(timestamp, boundaries[0], boundaries[boundaries.length - 1]);
        assertEq(cadence.cadencePeriodStart(timestamp), _largestAtMost(timestamp));
    }

    /// @dev Beyond the fixture's horizon the properties still hold (structural, not exact): a Friday at 15:00:00
    /// UTC at or before the input, a fixed point, and no more than five weeks in the past. Unlike the Solady
    /// variant (undefined above ~year 4.29e9), the inline math stays well-defined out to ~year 9000 here.
    function testFuzz_structuralBeyondFixture(uint256 timestamp) public view {
        timestamp = bound(timestamp, boundaries[boundaries.length - 1], DOMAIN_END);
        uint256 b = cadence.cadencePeriodStart(timestamp);
        assertLe(b, timestamp);
        assertEq(cadence.cadencePeriodStart(b), b); // fixed point
        assertTrue(isFridayAt(b, BOUNDARY_TIME_OF_DAY));
        assertGt(b + 35 days, timestamp); // no boundary skipped
    }

    function testFuzz_idempotent(uint256 timestamp) public view {
        timestamp = bound(timestamp, DOMAIN_START, DOMAIN_END);
        uint256 b = cadence.cadencePeriodStart(timestamp);
        assertEq(cadence.cadencePeriodStart(b), b);
    }

    function testFuzz_monotonic(uint256 earlier, uint256 later) public view {
        earlier = bound(earlier, DOMAIN_START, DOMAIN_END);
        later = bound(later, DOMAIN_START, DOMAIN_END);
        if (earlier > later) (earlier, later) = (later, earlier);
        assertLe(cadence.cadencePeriodStart(earlier), cadence.cadencePeriodStart(later));
    }

    /// @dev Hardcoded epoch edge: the first boundary the contract can return is 1970-01-30 15:00:00 UTC; earlier
    /// inputs revert on arithmetic underflow.
    function test_epochEdges() public {
        assertEq(cadence.cadencePeriodStart(DOMAIN_START), DOMAIN_START);
        vm.expectRevert(stdError.arithmeticError);
        cadence.cadencePeriodStart(DOMAIN_START - 1);
    }

    /// @dev Largest fixture boundary at or before `t` (t is bounded at or above the first entry). Binary search
    /// over the loaded values - the fixture is the only oracle, no calendar arithmetic.
    function _largestAtMost(uint256 t) internal view returns (uint256) {
        uint256 lo;
        uint256 hi = boundaries.length;
        while (lo < hi) {
            uint256 mid = (lo + hi) >> 1;
            if (boundaries[mid] <= t) {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        return boundaries[lo - 1];
    }
}
