// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";
import {LastFridayOfMonthCadence} from "../../src/ratifiers/policies/LastFridayOfMonthCadence.sol";
import {
    SECONDS_PER_DAY,
    BOUNDARY_TIME_OF_DAY,
    DOMAIN_START,
    DOMAIN_END,
    FIXTURE_ENTRY_COUNT,
    isFridayAt,
    isLastFridayOfMonth
} from "../helpers/CadenceTestConstants.sol";

/// @dev No-dependency variant, validated against a hardcoded golden fixture rather than a Solidity reference.
/// Every expected boundary in test/fixtures/last_friday_boundaries.txt was generated by Python's calendar/datetime
/// modules (see the sibling .py), which share no code and no algorithm with the contract's inlined Hinnant math.
/// The test therefore contains NO civil-date arithmetic of its own: it treats the file as the specification and
/// checks the contract reproduces it exactly, so a bug common to the contract and any hand-written Solidity
/// reference cannot hide. Coverage beyond the fixture's horizon is structural (properties, not exact values).
contract LastFridayOfMonthCadenceTest is Test {
    LastFridayOfMonthCadence cadence;

    /// @dev Hardcoded boundaries loaded from the fixture (2025-01 .. 2125-12, last Friday of month, 15:00:00 UTC).
    uint256[] internal boundaries;

    function setUp() public {
        cadence = new LastFridayOfMonthCadence(BOUNDARY_TIME_OF_DAY);
        string[] memory lines = vm.split(vm.readFile("test/fixtures/last_friday_boundaries.txt"), "\n");
        for (uint256 i; i < lines.length; ++i) {
            if (bytes(lines[i]).length == 0) continue; // trailing newline
            boundaries.push(vm.parseUint(lines[i]));
        }
        // Exact count, so a truncated or blank-line-corrupted fixture cannot load silently.
        assertEq(boundaries.length, FIXTURE_ENTRY_COUNT, "fixture failed to load");
    }

    /// @dev Guards the oracle itself: the fixture must be strictly increasing, every entry a Friday at 15:00:00
    /// UTC and the LAST Friday of its month, and consecutive entries 28 or 35 days apart. The weekday check is a
    /// plain epoch-day parity and the last-of-month check an additive month walk, neither being the contract's
    /// month algorithm, so both independently catch a corrupted or mis-generated file. Without the last-of-month
    /// check a generator emitting the second-to-last Friday would produce a file that is still strictly
    /// increasing, still all Fridays, and still 28 or 35 days apart.
    function test_fixtureIsWellFormed() public view {
        for (uint256 i; i < boundaries.length; ++i) {
            uint256 b = boundaries[i];
            assertTrue(isFridayAt(b, BOUNDARY_TIME_OF_DAY), "not a Friday at 15:00:00 UTC");
            assertTrue(isLastFridayOfMonth(b), "not the last Friday of its month");
            if (i > 0) {
                uint256 gap = b - boundaries[i - 1];
                assertTrue(gap == 28 days || gap == 35 days, "gap is not four or five weeks");
            }
        }
    }

    /// @dev The core check: every hardcoded boundary is an exact fixed point, one second later still maps to it,
    /// most of the period maps back, and one second before maps to the previous fixture entry. No date math here -
    /// the expected values come entirely from the file.
    function test_everyBoundaryMatchesFixture() public view {
        for (uint256 i; i < boundaries.length; ++i) {
            uint256 b = boundaries[i];
            assertEq(cadence.cadencePeriodStart(b), b);
            assertEq(cadence.cadencePeriodStart(b + 1), b);
            assertEq(cadence.cadencePeriodStart(b + 27 days), b); // shortest period is 28 days
            if (i > 0) assertEq(cadence.cadencePeriodStart(b - 1), boundaries[i - 1]);
        }
    }

    /// @dev Continuous differential fuzz against the fixture: for any timestamp inside the covered range, the
    /// contract must return the largest hardcoded boundary at or before it (found by binary search over the file).
    function testFuzz_matchesFixture(uint256 timestamp) public view {
        // Only the covered range: past the last entry the true boundary (next month) is not in the file.
        timestamp = bound(timestamp, boundaries[0], boundaries[boundaries.length - 1]);
        assertEq(cadence.cadencePeriodStart(timestamp), _largestAtMost(timestamp));
    }

    /// @dev Beyond the fixture's horizon the properties still hold (structural, not exact): the LAST Friday of a
    /// month, at 15:00:00 UTC, at or before the input, a fixed point, and no more than five weeks in the past.
    /// Unlike the Solady variant (undefined above ~year 4.29e9), the inline math stays well-defined out to
    /// ~year 9000 here.
    function testFuzz_structuralBeyondFixture(uint256 timestamp) public view {
        timestamp = bound(timestamp, boundaries[boundaries.length - 1], DOMAIN_END);
        _assertStructural(timestamp);
    }

    /// @dev The same properties above the chosen ~year 9000 horizon, out to type(uint256).max. The inline math has
    /// no ceiling (civil_from_days stays exact for any epoch day). The unchecked-equivalence suite already rules
    /// out a silent wrap, since a wrap would make its fully-checked twin revert and break parity; what it cannot
    /// give is the VALUE, because the twin shares the algorithm. That is what this pins.
    function testFuzz_structuralAtExtremeTimestamps(uint256 timestamp) public view {
        timestamp = bound(timestamp, DOMAIN_END, type(uint256).max);
        _assertStructural(timestamp);
    }

    /// @dev Log-uniform companion to the test above. Bounding uniformly over [DOMAIN_END, type(uint256).max] draws
    /// essentially every sample above 2**250, leaving the whole band between the horizon and 2**64 unexercised.
    /// Fuzzing the magnitude first spreads the samples evenly across the exponents instead.
    function testFuzz_structuralAcrossMagnitudes(uint256 magnitude, uint256 timestamp) public view {
        magnitude = bound(magnitude, 38, 256); // DOMAIN_END is just under 2**38
        uint256 upper = magnitude == 256 ? type(uint256).max : 2 ** magnitude - 1;
        timestamp = bound(timestamp, DOMAIN_END, upper);
        _assertStructural(timestamp);
    }

    /// @dev Hardcoded upper edge, the counterpart of test_epochEdges. Fuzzing samples the domain but never lands
    /// on its extremes, and the unchecked-equivalence suite only pins that the shipped contract and its checked
    /// twin AGREE there, which a drift shared by both would survive. These are absolute assertions at the largest
    /// inputs the contract can be called with: it must not revert, and the boundary must be the uniquely correct
    /// one. Its being at or before the input is what BaseMigrationRatifier._ratifyWindow relies on to not revert
    /// with InvalidRenewalParams, and it is also what makes the final `boundary * 1 days + BOUNDARY_TIME_OF_DAY`
    /// safe to leave unchecked.
    function test_extremeInputsStayStructurallyValid() public view {
        uint256[6] memory inputs = [DOMAIN_END, 2 ** 64, 2 ** 128, 2 ** 200, type(uint256).max - 1, type(uint256).max];
        for (uint256 i; i < inputs.length; ++i) {
            _assertStructural(inputs[i]);
        }
    }

    function testFuzz_idempotent(uint256 timestamp) public view {
        timestamp = bound(timestamp, DOMAIN_START, DOMAIN_END);
        uint256 b = cadence.cadencePeriodStart(timestamp);
        assertEq(cadence.cadencePeriodStart(b), b);
    }

    function testFuzz_monotonic(uint256 earlier, uint256 later) public view {
        earlier = bound(earlier, DOMAIN_START, DOMAIN_END);
        later = bound(later, DOMAIN_START, DOMAIN_END);
        if (earlier > later) (earlier, later) = (later, earlier);
        assertLe(cadence.cadencePeriodStart(earlier), cadence.cadencePeriodStart(later));
    }

    /// @dev Hardcoded epoch edge: the first boundary the contract can return is 1970-01-30 15:00:00 UTC; earlier
    /// inputs revert. The hardcoded floor also pins the constructor-computed FIRST_BOUNDARY.
    function test_epochEdges() public {
        assertEq(cadence.FIRST_BOUNDARY(), DOMAIN_START);
        assertEq(cadence.cadencePeriodStart(DOMAIN_START), DOMAIN_START);
        vm.expectRevert(LastFridayOfMonthCadence.TimestampBeforeFirstBoundary.selector);
        cadence.cadencePeriodStart(DOMAIN_START - 1);
    }

    /// @dev Every property the cadence must hold outside the fixture's horizon, where no hardcoded expected value
    /// exists. Together these pin the boundary uniquely: it is the last Friday of a month (not the second-to-last,
    /// which satisfies all the others), at the configured time, at or before the input, and no later boundary sits
    /// between it and the input.
    function _assertStructural(uint256 timestamp) internal view {
        uint256 b = cadence.cadencePeriodStart(timestamp);
        // BaseMigrationRatifier._ratifyWindow reverts if the cadence returns a future period start.
        assertLe(b, timestamp, "period start is after the queried timestamp");
        // BaseMigrationRatifier._validateTargetMaturity accepts a maturity only if it is a fixed point.
        assertEq(cadence.cadencePeriodStart(b), b, "boundary is not a fixed point");
        assertTrue(isFridayAt(b, BOUNDARY_TIME_OF_DAY), "not a Friday at 15:00:00 UTC");
        assertTrue(isLastFridayOfMonth(b), "not the last Friday of its month");
        // Subtracting rather than adding 35 days keeps the check meaningful at type(uint256).max.
        assertLt(timestamp - b, 35 days, "boundary is more than five weeks before the timestamp");
        // The five-week bound alone does NOT pin the boundary: when the preceding gap is 28 days, the PREVIOUS
        // boundary also lands within five weeks of any input in the first week of the period, and satisfies every
        // assertion above (it too is a last Friday, a fixed point, at or before the input). Consecutive last
        // Fridays are exactly 28 or 35 days apart, so given the bound above the only boundary that could have
        // been skipped is the one 28 days on; ruling it out makes the answer unique. `b + 28 days` cannot
        // overflow here because the guard establishes `b + 28 days <= timestamp`.
        if (timestamp - b >= 28 days) {
            assertFalse(isLastFridayOfMonth(b + 28 days), "skipped the boundary 28 days later");
        }
    }

    /// @dev Largest fixture boundary at or before `t` (t is bounded at or above the first entry). Binary search
    /// over the loaded values - the fixture is the only oracle, no calendar arithmetic.
    function _largestAtMost(uint256 t) internal view returns (uint256) {
        uint256 lo;
        uint256 hi = boundaries.length;
        while (lo < hi) {
            uint256 mid = (lo + hi) >> 1;
            if (boundaries[mid] <= t) {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        return boundaries[lo - 1];
    }
}
