// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.0;

import {Test, stdError} from "forge-std/Test.sol";
import {LastWeekdayOfMonthCadence} from "../../src/ratifiers/policies/LastWeekdayOfMonthCadence.sol";
import {
    SECONDS_PER_DAY,
    BOUNDARY_TIME_OF_DAY,
    DOMAIN_END,
    FIXTURE_ENTRY_COUNT,
    domainStart,
    isWeekdayAt
} from "../helpers/CadenceTestConstants.sol";

/// @dev No-dependency variant, validated against hardcoded golden fixtures rather than a Solidity reference.
/// Every expected boundary in test/fixtures/last_<weekday>_boundaries.txt (one file per Monday-indexed weekday)
/// was generated by Python's calendar/datetime modules (see the sibling .py), which share no code and no
/// algorithm with the contract's inlined Hinnant math. The test therefore contains NO civil-date arithmetic of
/// its own: it treats the files as the specification and checks the contract reproduces them exactly, so a bug
/// common to the contract and any hand-written Solidity reference cannot hide. Coverage beyond the fixtures'
/// horizon is structural (properties, not exact values).
contract LastWeekdayOfMonthCadenceTest is Test {
    LastWeekdayOfMonthCadence[7] internal cadences;

    /// @dev Hardcoded boundaries loaded per weekday from the fixtures (2025-01 .. 2125-12, last such weekday of
    /// month, 15:00:00 UTC).
    uint256[][7] internal boundaries;

    function setUp() public {
        string[7] memory names = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];
        for (uint256 w; w < 7; ++w) {
            cadences[w] = new LastWeekdayOfMonthCadence(w, BOUNDARY_TIME_OF_DAY);
            string memory path = string.concat("test/fixtures/last_", names[w], "_boundaries.txt");
            string[] memory lines = vm.split(vm.readFile(path), "\n");
            for (uint256 i; i < lines.length; ++i) {
                if (bytes(lines[i]).length == 0) continue; // trailing newline
                boundaries[w].push(vm.parseUint(lines[i]));
            }
            // Exact count, so a truncated or blank-line-corrupted fixture cannot load silently.
            assertEq(boundaries[w].length, FIXTURE_ENTRY_COUNT, "fixture failed to load");
        }
    }

    /// @dev Guards the oracles themselves: each fixture must be strictly increasing, every entry the file's
    /// weekday at 15:00:00 UTC, and consecutive entries 28 or 35 days apart. The weekday check is a plain
    /// epoch-day parity, not the contract's month algorithm, so it independently catches a corrupted or
    /// mis-generated file.
    function test_fixtureIsWellFormed() public view {
        for (uint256 w; w < 7; ++w) {
            for (uint256 i; i < boundaries[w].length; ++i) {
                uint256 b = boundaries[w][i];
                assertTrue(isWeekdayAt(b, w, BOUNDARY_TIME_OF_DAY), "not the fixture's weekday at 15:00:00 UTC");
                if (i > 0) {
                    uint256 gap = b - boundaries[w][i - 1];
                    assertTrue(gap == 28 days || gap == 35 days, "gap is not four or five weeks");
                }
            }
        }
    }

    /// @dev The core check: for every weekday, every hardcoded boundary is an exact fixed point, one second
    /// later still maps to it, most of the period maps back, and one second before maps to the previous fixture
    /// entry. No date math here - the expected values come entirely from the files.
    function test_everyBoundaryMatchesFixture() public view {
        for (uint256 w; w < 7; ++w) {
            for (uint256 i; i < boundaries[w].length; ++i) {
                uint256 b = boundaries[w][i];
                assertEq(cadences[w].cadencePeriodStart(b), b);
                assertEq(cadences[w].cadencePeriodStart(b + 1), b);
                assertEq(cadences[w].cadencePeriodStart(b + 27 days), b); // shortest period is 28 days
                if (i > 0) assertEq(cadences[w].cadencePeriodStart(b - 1), boundaries[w][i - 1]);
            }
        }
    }

    /// @dev Continuous differential fuzz against the fixtures: for any weekday and any timestamp inside the
    /// covered range, the contract must return the largest hardcoded boundary at or before it (found by binary
    /// search over the file).
    function testFuzz_matchesFixture(uint256 weekday, uint256 timestamp) public view {
        uint256 w = bound(weekday, 0, 6);
        // Only the covered range: past the last entry the true boundary (next month) is not in the file.
        timestamp = bound(timestamp, boundaries[w][0], boundaries[w][boundaries[w].length - 1]);
        assertEq(cadences[w].cadencePeriodStart(timestamp), _largestAtMost(w, timestamp));
    }

    /// @dev Beyond the fixtures' horizon the properties still hold (structural, not exact): the configured
    /// weekday at 15:00:00 UTC at or before the input, a fixed point, and no more than five weeks in the past.
    /// Unlike the Solady variant (undefined above ~year 4.29e9), the inline math stays well-defined out to
    /// ~year 9000 here.
    function testFuzz_structuralBeyondFixture(uint256 weekday, uint256 timestamp) public view {
        uint256 w = bound(weekday, 0, 6);
        timestamp = bound(timestamp, boundaries[w][boundaries[w].length - 1], DOMAIN_END);
        uint256 b = cadences[w].cadencePeriodStart(timestamp);
        assertLe(b, timestamp);
        assertEq(cadences[w].cadencePeriodStart(b), b); // fixed point
        assertTrue(isWeekdayAt(b, w, BOUNDARY_TIME_OF_DAY));
        assertGt(b + 35 days, timestamp); // no boundary skipped
    }

    function testFuzz_idempotent(uint256 weekday, uint256 timestamp) public view {
        uint256 w = bound(weekday, 0, 6);
        timestamp = bound(timestamp, domainStart(w), DOMAIN_END);
        uint256 b = cadences[w].cadencePeriodStart(timestamp);
        assertEq(cadences[w].cadencePeriodStart(b), b);
    }

    function testFuzz_monotonic(uint256 weekday, uint256 earlier, uint256 later) public view {
        uint256 w = bound(weekday, 0, 6);
        earlier = bound(earlier, domainStart(w), DOMAIN_END);
        later = bound(later, domainStart(w), DOMAIN_END);
        if (earlier > later) (earlier, later) = (later, earlier);
        assertLe(cadences[w].cadencePeriodStart(earlier), cadences[w].cadencePeriodStart(later));
    }

    /// @dev Hardcoded epoch edge: for each weekday the first boundary the contract can return is the last such
    /// weekday of January 1970; earlier inputs revert on arithmetic underflow.
    function test_epochEdges() public {
        for (uint256 w; w < 7; ++w) {
            uint256 first = domainStart(w);
            assertEq(cadences[w].cadencePeriodStart(first), first);
            vm.expectRevert(stdError.arithmeticError);
            cadences[w].cadencePeriodStart(first - 1);
        }
    }

    /// @dev Largest fixture boundary for weekday `w` at or before `t` (t is bounded at or above the first
    /// entry). Binary search over the loaded values - the fixture is the only oracle, no calendar arithmetic.
    function _largestAtMost(uint256 w, uint256 t) internal view returns (uint256) {
        uint256 lo;
        uint256 hi = boundaries[w].length;
        while (lo < hi) {
            uint256 mid = (lo + hi) >> 1;
            if (boundaries[w][mid] <= t) {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        return boundaries[w][lo - 1];
    }
}
